//user
//当前基础用户信息
export const USER_CURRENT_SUMMONER = "USER_CURRENT_SUMMONER";
//设置用户头像
export const USER_SET_SUMMONER_AVATAR = "USER_SET_SUMMONER_AVATAR";
//设置用户状态
export const USER_SET_SUMMONER_STATUS = "USER_SET_SUMMONER_STATUS";
